KEYWORD_MAP = {
        "ip address": "Computer Networks",
        "ipv4": "Computer Networks",
        "ipv6": "Computer Networks",
        "subnet": "Computer Networks",
        "subnetting": "Computer Networks",
        "subnet mask": "Computer Networks",
        "default gateway": "Computer Networks",
        "mac address": "Computer Networks",
        "arp": "Computer Networks",
        "rarp": "Computer Networks",
        "dns": "Computer Networks",
        "dhcp": "Computer Networks",
        "tcp": "Computer Networks",
        "udp": "Computer Networks",
        "tcp/ip": "Computer Networks",
        "http": "Computer Networks",
        "https": "Computer Networks",
        "ftp": "Computer Networks",
        "sftp": "Computer Networks",
        "ssh": "Computer Networks",
        "telnet": "Computer Networks",
        "smtp": "Computer Networks",
        "pop3": "Computer Networks",
        "imap": "Computer Networks",
        "router": "Computer Networks",
        "switch": "Computer Networks",
        "hub": "Computer Networks",
        "bridge": "Computer Networks",
        "gateway": "Computer Networks",
        "modem": "Computer Networks",
        "firewall": "Computer Networks",
        "proxy": "Computer Networks",
        "network": "Computer Networks",
        "network topology": "Computer Networks",
        "lan": "Computer Networks",
        "wan": "Computer Networks",
        "man": "Computer Networks",
        "pan": "Computer Networks",
        "wlan": "Computer Networks",
        "ethernet": "Computer Networks",
        "wi-fi": "Computer Networks",
        "bandwidth": "Computer Networks",
        "latency": "Computer Networks",
        "packet": "Computer Networks",
        "packet switching": "Computer Networks",
        "circuit switching": "Computer Networks",
        "routing": "Computer Networks",
        "routing table": "Computer Networks",
        "static routing": "Computer Networks",
        "dynamic routing": "Computer Networks",
        "rip": "Computer Networks",
        "ospf": "Computer Networks",
        "bgp": "Computer Networks",
        "network layer": "Computer Networks",
        "transport layer": "Computer Networks",
        "application layer": "Computer Networks",
        "data link layer": "Computer Networks",
        "physical layer": "Computer Networks",
        "osi model": "Computer Networks",
        "osi": "Computer Networks",
        "network protocol": "Computer Networks",
        "collision domain": "Computer Networks",
        "broadcast domain": "Computer Networks",
        "csma/cd": "Computer Networks",
        "csma/ca": "Computer Networks",
        "full duplex": "Computer Networks",
        "half duplex": "Computer Networks",
        "unicast": "Computer Networks",
        "multicast": "Computer Networks",
        "broadcast": "Computer Networks",
        "socket": "Computer Networks",
        "port number": "Computer Networks",
        "port": "Computer Networks",
        "nat": "Computer Networks",
        "vpn": "Computer Networks",
        "voip": "Computer Networks",
        "network security": "Computer Networks",
        "programming": "Programming",
        "algorithm": "Programming",
        "code": "Programming",
        "syntax": "Programming",
        "variable": "Programming",
        "constant": "Programming",
        "data type": "Programming",
        "integer": "Programming",
        "float": "Programming",
        "double": "Programming",
        "character": "Programming",
        "string": "Programming",
        "boolean": "Programming",
        "operator": "Programming",
        "expression": "Programming",
        "statement": "Programming",
        "conditional": "Programming",
        "if statement": "Programming",
        "if else": "Programming",
        "switch": "Programming",
        "loop": "Programming",
        "for loop": "Programming",
        "while loop": "Programming",
        "do while": "Programming",
        "nested loop": "Programming",
        "function": "Programming",
        "method": "Programming",
        "parameter": "Programming",
        "argument": "Programming",
        "return value": "Programming",
        "recursion": "Programming",
        "iteration": "Programming",
        "array": "Programming",
        "string manipulation": "Programming",
        "input": "Programming",
        "output": "Programming",
        "exception": "Programming",
        "exception handling": "Programming",
        "debugging": "Programming",
        "compiler": "Programming",
        "interpreter": "Programming",
        "source code": "Programming",
        "executable": "Programming",
        "library": "Programming",
        "module": "Programming",
        "package": "Programming",
        "namespace": "Programming",
        "pointer": "Programming",
        "reference": "Programming",
        "memory allocation": "Programming",
        "syntax error": "Programming",
        "runtime error": "Programming",
        "logic error": "Programming",
        "class": "Object-Oriented Programming",
        "object": "Object-Oriented Programming",
        "oop": "Object-Oriented Programming",
        "object oriented": "Object-Oriented Programming",
        "object-oriented": "Object-Oriented Programming",
        "constructor": "Object-Oriented Programming",
        "destructor": "Object-Oriented Programming",
        "inheritance": "Object-Oriented Programming",
        "polymorphism": "Object-Oriented Programming",
        "encapsulation": "Object-Oriented Programming",
        "abstraction": "Object-Oriented Programming",
        "superclass": "Object-Oriented Programming",
        "subclass": "Object-Oriented Programming",
        "parent class": "Object-Oriented Programming",
        "child class": "Object-Oriented Programming",
        "base class": "Object-Oriented Programming",
        "derived class": "Object-Oriented Programming",
        "interface": "Object-Oriented Programming",
        "abstract class": "Object-Oriented Programming",
        "abstract method": "Object-Oriented Programming",
        "override": "Object-Oriented Programming",
        "overloading": "Object-Oriented Programming",
        "method overriding": "Object-Oriented Programming",
        "method overloading": "Object-Oriented Programming",
        "static": "Object-Oriented Programming",
        "this": "Object-Oriented Programming",
        "super": "Object-Oriented Programming",
        "access modifier": "Object-Oriented Programming",
        "public": "Object-Oriented Programming",
        "private": "Object-Oriented Programming",
        "protected": "Object-Oriented Programming",
        "getter": "Object-Oriented Programming",
        "setter": "Object-Oriented Programming",
        "data structure": "Data Structures",
        "array": "Data Structures",
        "linked list": "Data Structures",
        "singly linked list": "Data Structures",
        "doubly linked list": "Data Structures",
        "circular linked list": "Data Structures",
        "stack": "Data Structures",
        "queue": "Data Structures",
        "deque": "Data Structures",
        "priority queue": "Data Structures",
        "tree": "Data Structures",
        "binary tree": "Data Structures",
        "binary search tree": "Data Structures",
        "bst": "Data Structures",
        "avl tree": "Data Structures",
        "heap": "Data Structures",
        "min heap": "Data Structures",
        "max heap": "Data Structures",
        "hash table": "Data Structures",
        "hashmap": "Data Structures",
        "hash map": "Data Structures",
        "hashtable": "Data Structures",
        "dictionary": "Data Structures",
        "graph": "Data Structures",
        "vertex": "Data Structures",
        "edge": "Data Structures",
        "adjacency matrix": "Data Structures",
        "adjacency list": "Data Structures",
        "trie": "Data Structures",
        "node": "Data Structures",
        "pointer": "Data Structures",
        "linked structure": "Data Structures",
        "algorithm": "Algorithms",
        "algorithm complexity": "Algorithms",
        "time complexity": "Algorithms",
        "space complexity": "Algorithms",
        "big o": "Algorithms",
        "big-o": "Algorithms",
        "big omega": "Algorithms",
        "big theta": "Algorithms",
        "asymptotic analysis": "Algorithms",
        "sorting": "Algorithms",
        "searching": "Algorithms",
        "linear search": "Algorithms",
        "binary search": "Algorithms",
        "bubble sort": "Algorithms",
        "selection sort": "Algorithms",
        "insertion sort": "Algorithms",
        "merge sort": "Algorithms",
        "quick sort": "Algorithms",
        "quicksort": "Algorithms",
        "heap sort": "Algorithms",
        "counting sort": "Algorithms",
        "radix sort": "Algorithms",
        "bucket sort": "Algorithms",
        "breadth first search": "Algorithms",
        "bfs": "Algorithms",
        "depth first search": "Algorithms",
        "dfs": "Algorithms",
        "dijkstra": "Algorithms",
        "bellman ford": "Algorithms",
        "floyd warshall": "Algorithms",
        "minimum spanning tree": "Algorithms",
        "kruskal": "Algorithms",
        "prim": "Algorithms",
        "greedy algorithm": "Algorithms",
        "dynamic programming": "Algorithms",
        "divide and conquer": "Algorithms",
        "backtracking": "Algorithms",
        "brute force": "Algorithms",
        "recursion": "Algorithms",
        "shortest path": "Algorithms",
        "topological sort": "Algorithms",
        "database": "Database",
        "dbms": "Database",
        "rdbms": "Database",
        "relational database": "Database",
        "table": "Database",
        "record": "Database",
        "field": "Database",
        "row": "Database",
        "column": "Database",
        "primary key": "Database",
        "foreign key": "Database",
        "candidate key": "Database",
        "composite key": "Database",
        "unique key": "Database",
        "sql": "Database",
        "mysql": "Database",
        "postgresql": "Database",
        "oracle database": "Database",
        "sqlite": "Database",
        "query": "Database",
        "select": "Database",
        "insert": "Database",
        "update": "Database",
        "delete": "Database",
        "join": "Database",
        "inner join": "Database",
        "left join": "Database",
        "right join": "Database",
        "full join": "Database",
        "cross join": "Database",
        "aggregate": "Database",
        "group by": "Database",
        "order by": "Database",
        "where clause": "Database",
        "having clause": "Database",
        "normalization": "Database",
        "denormalization": "Database",
        "1nf": "Database",
        "2nf": "Database",
        "3nf": "Database",
        "bcnf": "Database",
        "functional dependency": "Database",
        "entity": "Database",
        "attribute": "Database",
        "relationship": "Database",
        "er diagram": "Database",
        "erd": "Database",
        "transaction": "Database",
        "acid": "Database",
        "atomicity": "Database",
        "consistency": "Database",
        "isolation": "Database",
        "durability": "Database",
        "concurrency control": "Database",
        "database schema": "Database",
        "database index": "Database",
        "stored procedure": "Database",
        "trigger": "Database",
        "view": "Database",
        "operating system": "Operating Systems",
        "os": "Operating Systems",
        "kernel": "Operating Systems",
        "process": "Operating Systems",
        "process state": "Operating Systems",
        "process scheduling": "Operating Systems",
        "thread": "Operating Systems",
        "multithreading": "Operating Systems",
        "multitasking": "Operating Systems",
        "multiprocessing": "Operating Systems",
        "cpu scheduling": "Operating Systems",
        "fcfs": "Operating Systems",
        "first come first serve": "Operating Systems",
        "sjf": "Operating Systems",
        "shortest job first": "Operating Systems",
        "round robin": "Operating Systems",
        "priority scheduling": "Operating Systems",
        "context switching": "Operating Systems",
        "deadlock": "Operating Systems",
        "deadlock prevention": "Operating Systems",
        "deadlock avoidance": "Operating Systems",
        "banker's algorithm": "Operating Systems",
        "semaphore": "Operating Systems",
        "mutex": "Operating Systems",
        "critical section": "Operating Systems",
        "race condition": "Operating Systems",
        "process synchronization": "Operating Systems",
        "virtual memory": "Operating Systems",
        "paging": "Operating Systems",
        "segmentation": "Operating Systems",
        "page fault": "Operating Systems",
        "page replacement": "Operating Systems",
        "fifo page replacement": "Operating Systems",
        "lru": "Operating Systems",
        "thrashing": "Operating Systems",
        "memory management": "Operating Systems",
        "file system": "Operating Systems",
        "file allocation": "Operating Systems",
        "disk scheduling": "Operating Systems",
        "system call": "Operating Systems",
        "user mode": "Operating Systems",
        "kernel mode": "Operating Systems",
        "booting": "Operating Systems",
        "linux": "Operating Systems",
        "unix": "Operating Systems",
        "computer architecture": "Computer Architecture",
        "cpu": "Computer Architecture",
        "processor": "Computer Architecture",
        "alu": "Computer Architecture",
        "control unit": "Computer Architecture",
        "register": "Computer Architecture",
        "program counter": "Computer Architecture",
        "instruction register": "Computer Architecture",
        "accumulator": "Computer Architecture",
        "cache": "Computer Architecture",
        "cache memory": "Computer Architecture",
        "cache hit": "Computer Architecture",
        "cache miss": "Computer Architecture",
        "cache mapping": "Computer Architecture",
        "direct mapping": "Computer Architecture",
        "associative mapping": "Computer Architecture",
        "set associative": "Computer Architecture",
        "memory hierarchy": "Computer Architecture",
        "ram": "Computer Architecture",
        "rom": "Computer Architecture",
        "dram": "Computer Architecture",
        "sram": "Computer Architecture",
        "virtual memory": "Computer Architecture",
        "address bus": "Computer Architecture",
        "data bus": "Computer Architecture",
        "control bus": "Computer Architecture",
        "bus": "Computer Architecture",
        "instruction": "Computer Architecture",
        "instruction set": "Computer Architecture",
        "isa": "Computer Architecture",
        "machine language": "Computer Architecture",
        "assembly language": "Computer Architecture",
        "assembly": "Computer Architecture",
        "opcode": "Computer Architecture",
        "operand": "Computer Architecture",
        "addressing mode": "Computer Architecture",
        "pipeline": "Computer Architecture",
        "instruction pipeline": "Computer Architecture",
        "pipeline hazard": "Computer Architecture",
        "data hazard": "Computer Architecture",
        "control hazard": "Computer Architecture",
        "branch prediction": "Computer Architecture",
        "risc": "Computer Architecture",
        "cisc": "Computer Architecture",
        "von neumann": "Computer Architecture",
        "harvard architecture": "Computer Architecture",
        "digital logic": "Digital Logic",
        "logic gate": "Digital Logic",
        "and gate": "Digital Logic",
        "or gate": "Digital Logic",
        "not gate": "Digital Logic",
        "nand gate": "Digital Logic",
        "nor gate": "Digital Logic",
        "xor gate": "Digital Logic",
        "xnor gate": "Digital Logic",
        "truth table": "Digital Logic",
        "boolean algebra": "Digital Logic",
        "boolean expression": "Digital Logic",
        "boolean function": "Digital Logic",
        "logic circuit": "Digital Logic",
        "combinational circuit": "Digital Logic",
        "sequential circuit": "Digital Logic",
        "k-map": "Digital Logic",
        "karnaugh map": "Digital Logic",
        "minterm": "Digital Logic",
        "maxterm": "Digital Logic",
        "sop": "Digital Logic",
        "sum of products": "Digital Logic",
        "pos": "Digital Logic",
        "product of sums": "Digital Logic",
        "don't care": "Digital Logic",
        "don't-care": "Digital Logic",
        "multiplexer": "Digital Logic",
        "mux": "Digital Logic",
        "demultiplexer": "Digital Logic",
        "demux": "Digital Logic",
        "encoder": "Digital Logic",
        "decoder": "Digital Logic",
        "half adder": "Digital Logic",
        "full adder": "Digital Logic",
        "flip flop": "Digital Logic",
        "flip-flop": "Digital Logic",
        "sr flip flop": "Digital Logic",
        "jk flip flop": "Digital Logic",
        "d flip flop": "Digital Logic",
        "t flip flop": "Digital Logic",
        "counter": "Digital Logic",
        "register": "Digital Logic",
        "shift register": "Digital Logic",
        "cybersecurity": "Cybersecurity",
        "cyber security": "Cybersecurity",
        "information security": "Cybersecurity",
        "security": "Cybersecurity",
        "encryption": "Cybersecurity",
        "decryption": "Cybersecurity",
        "cryptography": "Cybersecurity",
        "cipher": "Cybersecurity",
        "plaintext": "Cybersecurity",
        "ciphertext": "Cybersecurity",
        "caesar cipher": "Cybersecurity",
        "substitution cipher": "Cybersecurity",
        "transposition cipher": "Cybersecurity",
        "rsa": "Cybersecurity",
        "aes": "Cybersecurity",
        "des": "Cybersecurity",
        "3des": "Cybersecurity",
        "hash": "Cybersecurity",
        "hashing": "Cybersecurity",
        "md5": "Cybersecurity",
        "sha": "Cybersecurity",
        "sha-256": "Cybersecurity",
        "digital signature": "Cybersecurity",
        "public key": "Cybersecurity",
        "private key": "Cybersecurity",
        "authentication": "Cybersecurity",
        "authorization": "Cybersecurity",
        "access control": "Cybersecurity",
        "malware": "Cybersecurity",
        "virus": "Cybersecurity",
        "worm": "Cybersecurity",
        "trojan": "Cybersecurity",
        "ransomware": "Cybersecurity",
        "spyware": "Cybersecurity",
        "phishing": "Cybersecurity",
        "social engineering": "Cybersecurity",
        "brute force attack": "Cybersecurity",
        "ddos": "Cybersecurity",
        "dos attack": "Cybersecurity",
        "sql injection": "Cybersecurity",
        "xss": "Cybersecurity",
        "cross site scripting": "Cybersecurity",
        "firewall": "Cybersecurity",
        "vulnerability": "Cybersecurity",
        "exploit": "Cybersecurity",
        "penetration testing": "Cybersecurity",
        "ethical hacking": "Cybersecurity",
        "software engineering": "Software Engineering",
        "software development": "Software Engineering",
        "software lifecycle": "Software Engineering",
        "sdlc": "Software Engineering",
        "requirements": "Software Engineering",
        "requirements engineering": "Software Engineering",
        "functional requirement": "Software Engineering",
        "non-functional requirement": "Software Engineering",
        "use case": "Software Engineering",
        "use case diagram": "Software Engineering",
        "software design": "Software Engineering",
        "software architecture": "Software Engineering",
        "uml": "Software Engineering",
        "class diagram": "Software Engineering",
        "sequence diagram": "Software Engineering",
        "activity diagram": "Software Engineering",
        "state diagram": "Software Engineering",
        "waterfall": "Software Engineering",
        "agile": "Software Engineering",
        "scrum": "Software Engineering",
        "sprint": "Software Engineering",
        "kanban": "Software Engineering",
        "prototype model": "Software Engineering",
        "spiral model": "Software Engineering",
        "testing": "Software Engineering",
        "unit testing": "Software Engineering",
        "integration testing": "Software Engineering",
        "system testing": "Software Engineering",
        "acceptance testing": "Software Engineering",
        "regression testing": "Software Engineering",
        "test case": "Software Engineering",
        "debugging": "Software Engineering",
        "maintenance": "Software Engineering",
        "version control": "Software Engineering",
        "git": "Software Engineering",
        "github": "Software Engineering",
        "code review": "Software Engineering",
        "web development": "Web Development",
        "website": "Web Development",
        "web application": "Web Development",
        "frontend": "Web Development",
        "front-end": "Web Development",
        "backend": "Web Development",
        "back-end": "Web Development",
        "full stack": "Web Development",
        "html": "Web Development",
        "css": "Web Development",
        "javascript": "Web Development",
        "dom": "Web Development",
        "json": "Web Development",
        "xml": "Web Development",
        "ajax": "Web Development",
        "api": "Web Development",
        "rest api": "Web Development",
        "rest": "Web Development",
        "endpoint": "Web Development",
        "node.js": "Web Development",
        "react": "Web Development",
        "angular": "Web Development",
        "vue": "Web Development",
        "bootstrap": "Web Development",
        "php": "Web Development",
        "web server": "Web Development",
        "client-side": "Web Development",
        "server-side": "Web Development",
        "cookie": "Web Development",
        "session": "Web Development",
        "artificial intelligence": "Artificial Intelligence",
        "artificial intelligence": "Artificial Intelligence",
        "ai": "Artificial Intelligence",
        "machine learning": "Artificial Intelligence",
        "ml": "Artificial Intelligence",
        "deep learning": "Artificial Intelligence",
        "neural network": "Artificial Intelligence",
        "artificial neural network": "Artificial Intelligence",
        "cnn": "Artificial Intelligence",
        "convolutional neural network": "Artificial Intelligence",
        "rnn": "Artificial Intelligence",
        "recurrent neural network": "Artificial Intelligence",
        "lstm": "Artificial Intelligence",
        "transformer": "Artificial Intelligence",
        "natural language processing": "Artificial Intelligence",
        "nlp": "Artificial Intelligence",
        "computer vision": "Artificial Intelligence",
        "training data": "Artificial Intelligence",
        "dataset": "Artificial Intelligence",
        "feature": "Artificial Intelligence",
        "feature extraction": "Artificial Intelligence",
        "classification": "Artificial Intelligence",
        "regression": "Artificial Intelligence",
        "clustering": "Artificial Intelligence",
        "supervised learning": "Artificial Intelligence",
        "unsupervised learning": "Artificial Intelligence",
        "reinforcement learning": "Artificial Intelligence",
        "decision tree": "Artificial Intelligence",
        "random forest": "Artificial Intelligence",
        "k-means": "Artificial Intelligence",
        "knn": "Artificial Intelligence",
        "support vector machine": "Artificial Intelligence",
        "svm": "Artificial Intelligence",
        "linear regression": "Artificial Intelligence",
        "logistic regression": "Artificial Intelligence",
        "overfitting": "Artificial Intelligence",
        "underfitting": "Artificial Intelligence",
        "training": "Artificial Intelligence",
        "testing data": "Artificial Intelligence",
        "validation data": "Artificial Intelligence",
        "accuracy": "Artificial Intelligence",
        "precision": "Artificial Intelligence",
        "recall": "Artificial Intelligence",
        "f1 score": "Artificial Intelligence",
        "confusion matrix": "Artificial Intelligence",
        "discrete mathematics": "Discrete Mathematics",
        "set": "Discrete Mathematics",
        "sets": "Discrete Mathematics",
        "subset": "Discrete Mathematics",
        "union": "Discrete Mathematics",
        "intersection": "Discrete Mathematics",
        "complement": "Discrete Mathematics",
        "cartesian product": "Discrete Mathematics",
        "relation": "Discrete Mathematics",
        "relations": "Discrete Mathematics",
        "function": "Discrete Mathematics",
        "proposition": "Discrete Mathematics",
        "propositional logic": "Discrete Mathematics",
        "predicate logic": "Discrete Mathematics",
        "predicate": "Discrete Mathematics",
        "truth table": "Discrete Mathematics",
        "logical equivalence": "Discrete Mathematics",
        "implication": "Discrete Mathematics",
        "biconditional": "Discrete Mathematics",
        "quantifier": "Discrete Mathematics",
        "proof": "Discrete Mathematics",
        "mathematical induction": "Discrete Mathematics",
        "induction": "Discrete Mathematics",
        "contradiction": "Discrete Mathematics",
        "contrapositive": "Discrete Mathematics",
        "permutation": "Discrete Mathematics",
        "combination": "Discrete Mathematics",
        "combinatorics": "Discrete Mathematics",
        "pigeonhole principle": "Discrete Mathematics",
        "recurrence relation": "Discrete Mathematics",
        "graph theory": "Discrete Mathematics",
        "tree": "Discrete Mathematics",
        "boolean algebra": "Discrete Mathematics",
        "embedded system": "Embedded Systems",
        "embedded systems": "Embedded Systems",
        "microcontroller": "Embedded Systems",
        "microprocessor": "Embedded Systems",
        "8051": "Embedded Systems",
        "arduino": "Embedded Systems",
        "raspberry pi": "Embedded Systems",
        "gpio": "Embedded Systems",
        "sensor": "Embedded Systems",
        "actuator": "Embedded Systems",
        "interrupt": "Embedded Systems",
        "timer": "Embedded Systems",
        "counter": "Embedded Systems",
        "uart": "Embedded Systems",
        "usart": "Embedded Systems",
        "spi": "Embedded Systems",
        "i2c": "Embedded Systems",
        "adc": "Embedded Systems",
        "dac": "Embedded Systems",
        "assembly language": "Embedded Systems",
        "assembly code": "Embedded Systems",
        "register": "Embedded Systems",
        "port": "Embedded Systems",
        "firmware": "Embedded Systems",
        "real-time system": "Embedded Systems",
        "rtos": "Embedded Systems",
        "mcu": "Embedded Systems",
        "computer graphics": "Computer Graphics",
        "graphics": "Computer Graphics",
        "pixel": "Computer Graphics",
        "resolution": "Computer Graphics",
        "bitmap": "Computer Graphics",
        "vector graphics": "Computer Graphics",
        "raster": "Computer Graphics",
        "rgb": "Computer Graphics",
        "color model": "Computer Graphics",
        "image processing": "Computer Graphics",
        "transformation": "Computer Graphics",
        "translation": "Computer Graphics",
        "rotation": "Computer Graphics",
        "scaling": "Computer Graphics",
        "reflection": "Computer Graphics",
        "clipping": "Computer Graphics",
        "rendering": "Computer Graphics",
        "3d graphics": "Computer Graphics",
        "2d graphics": "Computer Graphics",
        "animation": "Computer Graphics",
        "multimedia": "Computer Graphics",
        "cloud computing": "Cloud Computing",
        "cloud": "Cloud Computing",
        "iaas": "Cloud Computing",
        "paas": "Cloud Computing",
        "saas": "Cloud Computing",
        "public cloud": "Cloud Computing",
        "private cloud": "Cloud Computing",
        "hybrid cloud": "Cloud Computing",
        "virtualization": "Cloud Computing",
        "virtual machine": "Cloud Computing",
        "container": "Cloud Computing",
        "docker": "Cloud Computing",
        "kubernetes": "Cloud Computing",
        "aws": "Cloud Computing",
        "azure": "Cloud Computing",
        "google cloud": "Cloud Computing",
        "serverless": "Cloud Computing",
        "cloud storage": "Cloud Computing",
        "scalability": "Cloud Computing",
        "theory of computation": "Theory of Computation",
        "automata": "Theory of Computation",
        "finite automata": "Theory of Computation",
        "finite state machine": "Theory of Computation",
        "dfa": "Theory of Computation",
        "nfa": "Theory of Computation",
        "regular expression": "Theory of Computation",
        "regular language": "Theory of Computation",
        "context free grammar": "Theory of Computation",
        "cfg": "Theory of Computation",
        "pushdown automata": "Theory of Computation",
        "pda": "Theory of Computation",
        "turing machine": "Theory of Computation",
        "turing machines": "Theory of Computation",
        "decidability": "Theory of Computation",
        "computability": "Theory of Computation",
        "halting problem": "Theory of Computation",
        "formal language": "Theory of Computation",
}